In [1]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
chandashekar8_ddxplus_path = kagglehub.dataset_download('chandashekar8/ddxplus')

print('Data source import complete.')

Downloading to /root/.cache/kagglehub/datasets/chandashekar8/ddxplus/1.archive...

100%|██████████| 178M/178M [00:03<00:00, 56.0MB/s]

Extracting files...

Data source import complete.

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [4]:
import pandas as pd
import os

train = pd.read_csv(os.path.join(chandashekar8_ddxplus_path, "train.csv"))   # path ko actual file name ke हिसाब से change karna

print(train.shape)
print(train.columns.tolist())

(1025602, 6)
['AGE', 'DIFFERENTIAL_DIAGNOSIS', 'SEX', 'PATHOLOGY', 'EVIDENCES', 'INITIAL_EVIDENCE']

In [5]:
print(train["PATHOLOGY"].value_counts())

PATHOLOGY
URTI                                        64368
Viral pharyngitis                           61642
Anemia                                      50665
HIV (initial infection)                     29013
Localized edema                             27825
Anaphylaxis                                 27718
Pulmonary embolism                          27468
Influenza                                   26812
Bronchitis                                  26400
Allergic sinusitis                          26203
Acute dystonic reactions                    25982
GERD                                        25979
Acute otitis media                          25917
Pneumonia                                   25761
Panic attack                                25019
Acute laryngitis                            24129
Guillain-Barré syndrome                     22867
Pericarditis                                22785
Sarcoidosis                                 21285
Possible NSTEMI / STEMI                     21260
Unstable angina                             21244
Atrial fibrillation                         21036
Cluster headache                            20804
Chronic rhinosinusitis                      20579
Inguinal hernia                             20235
Bronchospasm / acute asthma exacerbation    19875
Acute pulmonary edema                       19018
Pancreatic neoplasm                         18846
Bronchiectasis                              18795
PSVT                                        18781
Myasthenia gravis                           18566
Scombroid food poisoning                    18535
Acute COPD exacerbation / infection         17661
Epiglottitis                                17209
Stable angina                               16995
Tuberculosis                                16245
Boerhaave                                   15080
Pulmonary neoplasm                          14457
Acute rhinosinusitis                        13578
SLE                                         11867
Myocarditis                                 11073
Larygospasm                                 10998
Spontaneous pneumothorax                    10162
Chagas                                       9252
Whooping cough                               6070
Spontaneous rib fracture                     5712
Croup                                        2852
Ebola                                         718
Bronchiolitis                                 261
Name: count, dtype: int64

In [6]:
import pandas as pd
import os

# ==============================
# Load DDXPlus Train Dataset
# ==============================

train = pd.read_csv(os.path.join(chandashekar8_ddxplus_path, "train.csv"))

TARGET = "PATHOLOGY"

sampled = []

for disease, group in train.groupby(TARGET):

    n = len(group)

    # ---------- Sampling Policy ----------

    if n <= 5000:
        take = n

    elif n <= 10000:
        take = 350

    elif n <= 20000:
        take = 550

    elif n <= 30000:
        take = 650

    else:
        take = 750

    sampled.append(
        group.sample(
            n=min(take, n),
            random_state=42
        )
    )

# Merge all diseases
sampled_df = pd.concat(sampled).reset_index(drop=True)

print("="*50)
print("Final Dataset Shape")
print(sampled_df.shape)

print("="*50)
print(sampled_df["PATHOLOGY"].value_counts())

sampled_df.to_csv("DDXPlus_22K.csv", index=False)

print("Saved Successfully!")

==================================================
Final Dataset Shape
(31331, 6)
==================================================
PATHOLOGY
Croup                                       2852
URTI                                         750
Viral pharyngitis                            750
Anemia                                       750
Ebola                                        718
Chronic rhinosinusitis                       650
Acute dystonic reactions                     650
Acute otitis media                           650
Acute laryngitis                             650
GERD                                         650
Cluster headache                             650
Guillain-Barré syndrome                      650
HIV (initial infection)                      650
Anaphylaxis                                  650
Allergic sinusitis                           650
Bronchitis                                   650
Atrial fibrillation                          650
Possible NSTEMI / STEMI                      650
Pulmonary embolism                           650
Unstable angina                              650
Sarcoidosis                                  650
Pneumonia                                    650
Pericarditis                                 650
Influenza                                    650
Inguinal hernia                              650
Panic attack                                 650
Localized edema                              650
Bronchiectasis                               550
Bronchospasm / acute asthma exacerbation     550
Boerhaave                                    550
Acute rhinosinusitis                         550
Acute pulmonary edema                        550
Acute COPD exacerbation / infection          550
Scombroid food poisoning                     550
SLE                                          550
Pancreatic neoplasm                          550
PSVT                                         550
Larygospasm                                  550
Epiglottitis                                 550
Myocarditis                                  550
Myasthenia gravis                            550
Stable angina                                550
Tuberculosis                                 550
Pulmonary neoplasm                           550
Spontaneous pneumothorax                     550
Spontaneous rib fracture                     350
Chagas                                       350
Whooping cough                               350
Bronchiolitis                                261
Name: count, dtype: int64
Saved Successfully!

In [7]:

print(sampled_df.isnull().sum())
print(sampled_df.duplicated().sum())
print(sampled_df["PATHOLOGY"].value_counts())

AGE                       0
DIFFERENTIAL_DIAGNOSIS    0
SEX                       0
PATHOLOGY                 0
EVIDENCES                 0
INITIAL_EVIDENCE          0
dtype: int64
122
PATHOLOGY
Croup                                       2852
URTI                                         750
Viral pharyngitis                            750
Anemia                                       750
Ebola                                        718
Chronic rhinosinusitis                       650
Acute dystonic reactions                     650
Acute otitis media                           650
Acute laryngitis                             650
GERD                                         650
Cluster headache                             650
Guillain-Barré syndrome                      650
HIV (initial infection)                      650
Anaphylaxis                                  650
Allergic sinusitis                           650
Bronchitis                                   650
Atrial fibrillation                          650
Possible NSTEMI / STEMI                      650
Pulmonary embolism                           650
Unstable angina                              650
Sarcoidosis                                  650
Pneumonia                                    650
Pericarditis                                 650
Influenza                                    650
Inguinal hernia                              650
Panic attack                                 650
Localized edema                              650
Bronchiectasis                               550
Bronchospasm / acute asthma exacerbation     550
Boerhaave                                    550
Acute rhinosinusitis                         550
Acute pulmonary edema                        550
Acute COPD exacerbation / infection          550
Scombroid food poisoning                     550
SLE                                          550
Pancreatic neoplasm                          550
PSVT                                         550
Larygospasm                                  550
Epiglottitis                                 550
Myocarditis                                  550
Myasthenia gravis                            550
Stable angina                                550
Tuberculosis                                 550
Pulmonary neoplasm                           550
Spontaneous pneumothorax                     550
Spontaneous rib fracture                     350
Chagas                                       350
Whooping cough                               350
Bronchiolitis                                261
Name: count, dtype: int64

In [8]:
print(sampled_df.shape)

(31331, 6)

In [9]:
print(sampled_df.head())

   AGE                             DIFFERENTIAL_DIAGNOSIS SEX  \
0   67  [['Bronchitis', 0.2429175698894958], ['Acute C...   M
1   51  [['Bronchitis', 0.307162506634128], ['Acute CO...   M
2   76  [['Acute COPD exacerbation / infection', 0.111...   M
3   68  [['Acute COPD exacerbation / infection', 0.102...   M
4   42  [['Acute COPD exacerbation / infection', 0.102...   M

                             PATHOLOGY  \
0  Acute COPD exacerbation / infection
1  Acute COPD exacerbation / infection
2  Acute COPD exacerbation / infection
3  Acute COPD exacerbation / infection
4  Acute COPD exacerbation / infection

                                           EVIDENCES INITIAL_EVIDENCE
0  ['E_72', 'E_77', 'E_123', 'E_199', 'E_200', 'E...            E_214
1  ['E_31', 'E_72', 'E_79', 'E_123', 'E_125', 'E_...            E_201
2  ['E_66', 'E_77', 'E_123', 'E_198', 'E_199', 'E...             E_66
3  ['E_31', 'E_66', 'E_72', 'E_123', 'E_125', 'E_...            E_201
4  ['E_66', 'E_79', 'E_123', 'E_125', 'E_198', 'E...            E_214

In [10]:
sampled_df.head()

,AGE,DIFFERENTIAL_DIAGNOSIS,SEX,PATHOLOGY,EVIDENCES,INITIAL_EVIDENCE
0,67,"[['Bronchitis', 0.2429175698894958], ['Acute C...",M,Acute COPD exacerbation / infection,"['E_72', 'E_77', 'E_123', 'E_199', 'E_200', 'E...",E_214
1,51,"[['Bronchitis', 0.307162506634128], ['Acute CO...",M,Acute COPD exacerbation / infection,"['E_31', 'E_72', 'E_79', 'E_123', 'E_125', 'E_...",E_201
2,76,"[['Acute COPD exacerbation / infection', 0.111...",M,Acute COPD exacerbation / infection,"['E_66', 'E_77', 'E_123', 'E_198', 'E_199', 'E...",E_66
3,68,"[['Acute COPD exacerbation / infection', 0.102...",M,Acute COPD exacerbation / infection,"['E_31', 'E_66', 'E_72', 'E_123', 'E_125', 'E_...",E_201
4,42,"[['Acute COPD exacerbation / infection', 0.102...",M,Acute COPD exacerbation / infection,"['E_66', 'E_79', 'E_123', 'E_125', 'E_198', 'E...",E_214

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

sampled_df["PATHOLOGY"] = label_encoder.fit_transform(sampled_df["PATHOLOGY"])

In [12]:
sampled_df["SEX"] = sampled_df["SEX"].map({
    "M":0,
    "F":1
})

In [13]:
sampled_df

,AGE,DIFFERENTIAL_DIAGNOSIS,SEX,PATHOLOGY,EVIDENCES,INITIAL_EVIDENCE
0,67,"[['Bronchitis', 0.2429175698894958], ['Acute C...",0,0,"['E_72', 'E_77', 'E_123', 'E_199', 'E_200', 'E...",E_214
1,51,"[['Bronchitis', 0.307162506634128], ['Acute CO...",0,0,"['E_31', 'E_72', 'E_79', 'E_123', 'E_125', 'E_...",E_201
2,76,"[['Acute COPD exacerbation / infection', 0.111...",0,0,"['E_66', 'E_77', 'E_123', 'E_198', 'E_199', 'E...",E_66
3,68,"[['Acute COPD exacerbation / infection', 0.102...",0,0,"['E_31', 'E_66', 'E_72', 'E_123', 'E_125', 'E_...",E_201
4,42,"[['Acute COPD exacerbation / infection', 0.102...",0,0,"['E_66', 'E_79', 'E_123', 'E_125', 'E_198', 'E...",E_214
...,...,...,...,...,...,...
31326,70,"[['Whooping cough', 0.5363081514145991], ['Bro...",1,48,"['E_112', 'E_124', 'E_166', 'E_203', 'E_204_@_...",E_203
31327,46,"[['Bronchitis', 0.5295150093660963], ['Whoopin...",0,48,"['E_40', 'E_70', 'E_112', 'E_124', 'E_166', 'E...",E_112
31328,14,"[['Bronchitis', 0.5295150093660963], ['Whoopin...",0,48,"['E_40', 'E_112', 'E_166', 'E_204_@_V_4', 'E_2...",E_166
31329,73,"[['Whooping cough', 0.5363081514145991], ['Bro...",0,48,"['E_40', 'E_70', 'E_112', 'E_124', 'E_166', 'E...",E_203
31330,100,"[['Bronchitis', 0.5295150093660963], ['Whoopin...",0,48,"['E_40', 'E_70', 'E_112', 'E_124', 'E_166', 'E...",E_166

In [14]:
sampled_df['DIFFERENTIAL_DIAGNOSIS'][0]

"[['Bronchitis', 0.2429175698894958], ['Acute COPD exacerbation / infection', 0.23755894143919773], ['Pneumonia', 0.19930537540479706], ['Bronchospasm / acute asthma exacerbation', 0.164595942261847], ['Bronchiectasis', 0.15562217100466239]]"

In [15]:
sampled_df['DIFFERENTIAL_DIAGNOSIS'][1]

"[['Bronchitis', 0.307162506634128], ['Acute COPD exacerbation / infection', 0.2553728284525689], ['Bronchospasm / acute asthma exacerbation', 0.24269183507242095], ['Anaphylaxis', 0.13658355944340111], ['Scombroid food poisoning', 0.05818927039748104]]"

In [16]:
sampled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31331 entries, 0 to 31330
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   AGE                     31331 non-null  int64
 1   DIFFERENTIAL_DIAGNOSIS  31331 non-null  object
 2   SEX                     31331 non-null  int64
 3   PATHOLOGY               31331 non-null  int64
 4   EVIDENCES               31331 non-null  object
 5   INITIAL_EVIDENCE        31331 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.4+ MB

In [17]:


print(sampled_df["INITIAL_EVIDENCE"].nunique())

# print(sampled_df["DIFFERENTIAL_DIAGNOSIS"].iloc[0])

# print(type(sampled_df["DIFFERENTIAL_DIAGNOSIS"].iloc[0]))

96

In [18]:
import json

In [19]:
import ast

In [23]:
import json
import os

print("Files in chandashekar8_ddxplus_path:")
print(os.listdir(chandashekar8_ddxplus_path))

with open(os.path.join(chandashekar8_ddxplus_path, "release_evidences.json"),"r",encoding="utf-8") as f:
    evidence_data=json.load(f)

Files in chandashekar8_ddxplus_path:
['test.csv', 'train.csv', 'validate.csv']

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/kagglehub/datasets/chandashekar8/ddxplus/versions/1/release_evidences.json'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
def build_evidence_vocab(evidences_data):

    # Special Tokens
    vocab = {
        "<PAD>": 0,
        "<UNK>": 1
    }

    idx = 2

    # Har evidence par loop
    for code, info in evidences_data.items():

        # Evidence type
        data_type = info.get("data_type", "B")

        # -----------------------------
        # Binary Evidence
        # -----------------------------
        if data_type == "B":

            vocab[code] = idx
            idx += 1

        # -----------------------------
        # Categorical / Multi-choice
        # -----------------------------
        else:

            possible_values = info.get("possible-values", {})

            for value in possible_values:

                token = f"{code}_@_{value}"

                vocab[token] = idx

                idx += 1

    return vocab

In [ ]:
evidence_vocab = build_evidence_vocab(evidence_data)

In [ ]:
print("Vocabulary Size :", len(evidence_vocab))

In [ ]:
import ast

def convert_evidences_to_ids(evidence_string, vocab):

    # String → List
    evidence_list = ast.literal_eval(evidence_string)

    # Token → ID
    evidence_ids = []

    for token in evidence_list:

        evidence_ids.append(
            vocab.get(token, vocab["<UNK>"])
        )

    return evidence_ids

In [ ]:
sampled_df["EVIDENCES"] = sampled_df["EVIDENCES"].apply(
    lambda x: convert_evidences_to_ids(x, evidence_vocab)
)

In [ ]:
sampled_df["EVIDENCES"].head()

In [ ]:
sampled_df.head()

In [ ]:
sampled_df["INITIAL_EVIDENCE"] = sampled_df["INITIAL_EVIDENCE"].apply(
    lambda x: evidence_vocab.get(x, evidence_vocab["<UNK>"])
)

In [ ]:
sampled_df[["INITIAL_EVIDENCE", "EVIDENCES"]].head()

In [ ]:
sampled_df

In [ ]:
train_df = sampled_df.drop(columns=["DIFFERENTIAL_DIAGNOSIS"])

In [ ]:
train_df.head()

In [ ]:
train_df["SEQUENCE"] = train_df.apply(
    lambda row: [row["INITIAL_EVIDENCE"]] + row["EVIDENCES"],
    axis=1
)

In [ ]:
train_df[["SEQUENCE", "PATHOLOGY"]].head()

In [ ]:
first_row = sampled_df.iloc[0]

print(first_row["INITIAL_EVIDENCE"])
print(first_row["EVIDENCES"][0])

In [ ]:
reverse_vocab = {v: k for k, v in evidence_vocab.items()}

print(reverse_vocab[first_row["EVIDENCES"][0]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

sampled_df["AGE"] = scaler.fit_transform(sampled_df[["AGE"]])

In [ ]:
import joblib

joblib.dump(scaler, "age_scaler.pkl")

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

In [ ]:
train_data, temp_data = train_test_split(
    train_df,
    test_size=0.20,
    stratify=train_df["PATHOLOGY"],
    random_state=42
)
val_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    stratify=temp_data["PATHOLOGY"],
    random_state=42
)

In [ ]:
print(len(train_data))
print(len(val_data))
print(len(test_data))

In [ ]:
import torch
from torch.utils.data import Dataset

class DDXDataset(Dataset):
    def __init__(self, data):
        self.sequences = data["SEQUENCE"].tolist()
        self.ages = torch.tensor(data["AGE"].values, dtype=torch.float32)
        self.sexes = torch.tensor(data["SEX"].values, dtype=torch.long)
        self.labels = torch.tensor(data["PATHOLOGY"].values, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        sequence = torch.tensor(self.sequences[idx], dtype=torch.long)
        age = self.ages[idx]
        sex = self.sexes[idx]
        label = self.labels[idx]
        return sequence, age, sex, label

train_dataset = DDXDataset(train_data)
val_dataset = DDXDataset(val_data)
test_dataset = DDXDataset(test_data)

In [ ]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    sequences, ages, sexes, labels = zip(*batch)

    lengths = torch.tensor(
        [len(seq) for seq in sequences],
        dtype=torch.long
    )

    sequences = pad_sequence(
        sequences,
        batch_first=True,
        padding_value=0
    )

    ages = torch.stack(ages)

    sexes = torch.stack(sexes)

    labels = torch.stack(labels)

    return sequences, lengths, ages, sexes, labels

In [ ]:
from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    collate_fn=collate_fn
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False,
    collate_fn=collate_fn
)

In [ ]:
sequences, lengths, ages, sexes, labels = next(iter(train_loader))

print("Sequences :", sequences.shape)
print("Lengths   :", lengths.shape)
print("Age       :", ages.shape)
print("Sex       :", sexes.shape)
print("Labels    :", labels.shape)

In [ ]:
import torch
import torch.nn as nn

class DiagnosisModel(nn.Module):

    def __init__(
        self,
        vocab_size,
        embedding_dim,
        hidden_dim,
        num_layers,
        num_classes,
        dropout=0.3
    ):

        super(DiagnosisModel, self).__init__()

        # -----------------------------
        # Embedding Layer
        # -----------------------------
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim,
            padding_idx=0
        )

        # -----------------------------
        # LSTM Layer
        # -----------------------------
        self.lstm = nn.LSTM(
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0,
            bidirectional=False
        )

        # -----------------------------
        # Dropout Layer
        # -----------------------------
        self.dropout = nn.Dropout(dropout)

        # -----------------------------
        # Final Classifier
        # -----------------------------
        self.fc = nn.Linear(
            hidden_dim + 2,
            num_classes
        )

    def forward(self, sequence, lengths, age, sex):

        # -----------------------------
        # Embedding
        # -----------------------------
        embedded = self.embedding(sequence)

        # -----------------------------
        # Pack padded sequences
        # -----------------------------
        packed = nn.utils.rnn.pack_padded_sequence(
            embedded,
            lengths.cpu(),
            batch_first=True,
            enforce_sorted=False
        )

        # -----------------------------
        # LSTM
        # -----------------------------
        packed_output, (hidden, cell) = self.lstm(packed)

        # -----------------------------
        # Last Hidden State
        # -----------------------------
        hidden = hidden[-1]

        # -----------------------------
        # Dropout
        # -----------------------------
        hidden = self.dropout(hidden)

        # -----------------------------
        # Concatenate Age & Sex
        # -----------------------------
        age = age.unsqueeze(1)
        sex = sex.unsqueeze(1)

        features = torch.cat(
            (hidden, age, sex),
            dim=1
        )

        # -----------------------------
        # Final Classification
        # -----------------------------
        output = self.fc(features)

        return output

In [ ]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = DiagnosisModel(
    vocab_size=len(evidence_vocab),
    embedding_dim=128,
    hidden_dim=128,
    num_layers=2,
    num_classes=49,
    dropout=0.3
)

model = model.to(device)

In [ ]:
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

scaler = torch.cuda.amp.GradScaler()

In [ ]:
# ==========================================
# Training + Validation (Single Loop)
# ==========================================

NUM_EPOCHS = 20
best_val_loss = float("inf")

train_losses = []
val_losses = []

train_accs = []
val_accs = []

for epoch in range(NUM_EPOCHS):

    # =====================================
    # TRAINING
    # =====================================
    model.train()

    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for sequences, lengths, ages, sexes, labels in train_loader:

        sequences = sequences.to(device)
        lengths = lengths.to(device)
        ages = ages.to(device)
        sexes = sexes.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast():

            outputs = model(
                sequences,
                lengths,
                ages,
                sexes
            )

            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss += loss.item()

        predictions = outputs.argmax(dim=1)

        train_correct += (predictions == labels).sum().item()
        train_total += labels.size(0)

    train_loss /= len(train_loader)
    train_acc = 100 * train_correct / train_total

    train_losses.append(train_loss)
    train_accs.append(train_acc)

    # =====================================
    # VALIDATION
    # =====================================
    model.eval()

    val_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():

        for sequences, lengths, ages, sexes, labels in val_loader:

            sequences = sequences.to(device)
            lengths = lengths.to(device)
            ages = ages.to(device)
            sexes = sexes.to(device)
            labels = labels.to(device)

            outputs = model(
                sequences,
                lengths,
                ages,
                sexes
            )

            loss = criterion(outputs, labels)

            val_loss += loss.item()

            predictions = outputs.argmax(dim=1)

            val_correct += (predictions == labels).sum().item()
            val_total += labels.size(0)

    val_loss /= len(val_loader)
    val_acc = 100 * val_correct / val_total

    val_losses.append(val_loss)
    val_accs.append(val_acc)

    # =====================================
    # PRINT RESULT
    # =====================================
    print("=" * 70)
    print(f"Epoch [{epoch+1}/{NUM_EPOCHS}]")

    print(f"Train Loss      : {train_loss:.4f}")
    print(f"Train Accuracy  : {train_acc:.2f}%")

    print(f"Validation Loss : {val_loss:.4f}")
    print(f"Validation Acc  : {val_acc:.2f}%")

    # =====================================
    # SAVE BEST MODEL
    # =====================================
    if val_loss < best_val_loss:

        best_val_loss = val_loss

        torch.save(model.state_dict(), "best_model.pth")

        print(" Best Model Saved")

print("\n Training Completed Successfully!")

In [ ]:
import matplotlib.pyplot as plt

# =====================================
# Loss Graph
# =====================================

plt.figure(figsize=(8,5))

plt.plot(
    train_losses,
    marker='o',
    linewidth=2,
    label="Train Loss"
)

plt.plot(
    val_losses,
    marker='s',
    linewidth=2,
    label="Validation Loss"
)

plt.title("Training vs Validation Loss")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.grid(True)

plt.legend()

plt.show()

In [ ]:

# Load Best Saved Model


model.load_state_dict(torch.load("best_model.pth"))

model.to(device)

model.eval()

print("Best Model Loaded Successfully")

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

def evaluate_model(model, loader, device):

    model.eval()

    all_predictions = []
    all_labels = []

    with torch.no_grad():

        for sequences, lengths, ages, sexes, labels in loader:

            sequences = sequences.to(device)
            lengths = lengths.to(device)
            ages = ages.to(device)
            sexes = sexes.to(device)

            outputs = model(
                sequences,
                lengths,
                ages,
                sexes
            )

            predictions = torch.argmax(outputs, dim=1)

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_labels.extend(
                labels.numpy()
            )

    return all_labels, all_predictions

In [ ]:
true_labels, predicted_labels = evaluate_model(
    model,
    test_loader,
    device
)

In [ ]:
accuracy = accuracy_score(
    true_labels,
    predicted_labels
)

print(f"Test Accuracy : {accuracy*100:.2f}%")

In [ ]:
precision = precision_score(
    true_labels,
    predicted_labels,
    average="weighted"
)

recall = recall_score(
    true_labels,
    predicted_labels,
    average="weighted"
)

f1 = f1_score(
    true_labels,
    predicted_labels,
    average="weighted"
)

print(f"Precision : {precision:.4f}")

print(f"Recall : {recall:.4f}")

print(f"F1 Score : {f1:.4f}")

In [ ]:
print(
    classification_report(
        true_labels,
        predicted_labels
    )
)

In [ ]:
import pandas as pd

report = classification_report(
    true_labels,
    predicted_labels,
    output_dict=True
)

report_df = pd.DataFrame(report).transpose()

report_df.head(49)

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

fig, ax = plt.subplots(figsize=(18,18))

disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot(
    cmap="Blues",
    ax=ax,
    xticks_rotation=90,
    colorbar=True,
    values_format=""
)

plt.title("Confusion Matrix", fontsize=18)

plt.show()

In [ ]:
test_data["PATHOLOGY"].value_counts().sort_index()

In [ ]:
print(sampled_df["PATHOLOGY"].value_counts().sort_index())